#!/bin/bash
# Test all decrypted iPod games with experimental GL HLE
#
# Usage: ./scripts/test_all_games.sh [timeout_seconds]
# Example: TIMEOUT=15 ./scripts/test_all_games.sh

GAMES_DIR="/Users/kurt/Downloads/16-ipod-games/Games_RO"
REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
REPORT="${REPO_DIR}/docs/game_tests/$(date +%Y%m%d_%H%M%S)_compatibility_report.md"
EAPP="${REPO_DIR}/target/release/eapp"
TIMEOUT_SECS="${1:-${TIMEOUT:-8}}"

echo "=== iPod Game Compatibility Test ==="
echo "Games: $GAMES_DIR"
echo "Report: $REPORT"
echo "Timeout: ${TIMEOUT_SECS}s per game"
echo ""

# Build eapp if needed
if [ ! -f "$EAPP" ]; then
    echo "Building eapp..."
    cd "$REPO_DIR"
    cargo build -p clicky-desktop --bin eapp --release 2>&1 | tail -5
fi

# Set env for GL HLE
export CLICKY_EXPERIMENTAL_GL_HLE=1
export CLICKY_GL_GATE_B=1
export CLICKY_GL_LIVE_CONTINUOUS=1
export CLICKY_GL_PRESENT_VFLIP=1
export RUST_LOG="EAPP_GL=info,EAPP=warn"

cd "$GAMES_DIR"

# Report header
cat > "$REPORT" << 'HEADER'
# iPod Game Compatibility Report - Clicky Emulator

**Date:** $(date)  
**Test:** Headless ${TIMEOUT_SECS}s runs with experimental GL HLE

## Summary

| Bundle | Game Name | Status | Draw Calls | Notes |
|--------|-----------|--------|------------|-------|
HEADER

# Known game names
names[11002]="TWA"
names[12345]="Vortex"
names[14004]="Ms. Pac-Man"
names[1500C]="Sims Bowling"
names[1500E]="Sims Pool"
names[1B200]="Lost"
names[33333]="Texas Hold'em"
names[44444]="Zuma"
names[50513]="Sudoku"
names[50514]="Solitaire"
names[55555]="Bejeweled"
names[66666]="Tetris"
names[77777]="Mahjong"
names[88888]="Mini Golf"
names[99999]="Cubis 2"
names[AAAAA]="Pac-Man"

# Test each game
for bundle in [0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F]/; do
    [ -d "$bundle" ] || continue
    bundle_id=$(echo "$bundle" | tr -d '/')
    name="${names[$bundle_id]:-Unknown}"
    
    echo "Testing: $bundle_id ($name)..."
    
    LOG_FILE="/tmp/test_${bundle_id}_$$.log"
    timeout "$TIMEOUT_SECS" "$EAPP" "$bundle_id" --headless > "$LOG_FILE" 2>&1 || true
    
    draws=$(grep -c "rasterized" "$LOG_FILE" 2>/dev/null || echo 0)
    errors=$(grep -ic "error\|panic\|fatal" "$LOG_FILE" 2>/dev/null || echo 0)
    
    # Determine status
    if [ "$draws" -gt 500 ] 2>/dev/null; then
        status="✅ WORKS"
        notes=""
    elif [ "$draws" -gt 50 ] 2>/dev/null; then
        status="⚠️ PARTIAL"
        notes="Limited rendering"
    elif [ "$draws" -gt 0 ] 2>/dev/null; then
        status="👀 BOOTS"
        notes="Dies early"
    else
        status="❌ FAIL"
        notes="No graphics"
    fi
    
    printf "  -> %s (%s draws)\n" "$status" "$draws"
    
    # Append to report
    printf "| %s | %s | %s | %s | %s |\n" "$bundle_id" "$name" "$status" "$draws" "$notes" >> "$REPORT"
    
    rm -f "$LOG_FILE"
done

# Add footer
cat >> "$REPORT" << 'FOOTER'

## Test Environment

```bash
CLICKY_EXPERIMENTAL_GL_HLE=1
CLICKY_GL_GATE_B=1
CLICKY_GL_LIVE_CONTINUOUS=1
CLICKY_GL_PRESENT_VFLIP=1
RUST_LOG=EAPP_GL=info,EAPP=warn
```

**Platform:** Apple Silicon macOS  
**Backend:** minifb headless  

## Legend

| Status | Meaning |
|--------|---------|
| ✅ WORKS | Full rendering, many frames |
| ⚠️ PARTIAL | Some graphics, dies mid-way |
| 👀 BOOTS | Starts but dies immediately |
| ❌ FAIL | No graphics output |

---
*Generated by clicky/scripts/test_all_games.sh*
FOOTER

echo ""
echo "=== Complete ==="
echo "Report: $REPORT"
echo ""
cat "$REPORT"
